version: '3.5'
services:
  documentserver:
    image: onlyoffice/documentserver
    restart: always
    container_name: documentserver
    hostname: documentserver.itzxa.local
    networks:
      - "onlyoffice-net"
    dns:
      - "192.168.1.10"
    ports:
      - "8080:80"
      - "6379"
    volumes:
      - /data/onlyoffice/documentserver/logs:/var/log/onlyoffice
      - /data/onlyoffice/documentserver/data:/var/www/onlyoffice/Data
      - /data/onlyoffice/documentserver/lib:/var/lib/onlyoffice
      - /data/onlyoffice/documentserver/db:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '2048M'
        reservations:
          cpus: '0.25'
          memory: '1024M'

  mysql:
    image: mysql:5.7
    restart: always
    container_name: onlyofficemysql
    hostname: onlyofficemysql.itzxa.local
    networks:
      - "onlyoffice-net"
    environment:
      MYSQL_ROOT_PASSWORD: "Zxa82813011@"
      MYSQL_DATABASE: onlyoffice
      MYSQL_USER: officeadmin
      MYSQL_PASSWORD: "@fficEADmin"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - /data/onlyoffice/mysql/data:/var/lib/mysql
      - /data/onlyoffice/mysql/initdb:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 192.168.1.10
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 2048M
        reservations:
          cpus: '0.05'
          memory: 256M
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://192.168.x.x:123"

  communityserver:
    depends_on:
      - mysql
      - documentserver
    links:
      - mysql
      - documentserver
    image: onlyoffice/communityserver
    restart: always
    container_name: communityserver
    hostname: communityserver.itzxa.local
    networks:
      - "onlyoffice-net"
    environment:
      MYSQL_SERVER_ROOT_PASSWORD: "Zxa82813011@"
      MYSQL_SERVER_DB_NAME: onlyoffice
      MYSQL_SERVER_HOST: onlyofficemysql.itzxa.local
      MYSQL_SERVER_USER: officeadmin
      MYSQL_SERVER_PASS: "@fficEADmin"
    volumes:
      - /data/onlyoffice/communityserver/data:/var/www/onlyoffice/Data
      - /data/onlyoffice/communityserver/logs:/var/log/onlyoffice
      - /etc/localtime:/etc/localtime:ro
    dns:
      - "192.168.1.10"
    ports:
      - "80:80"
      - "443:443"
      - "5222:5222"
      - "6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4096M
        reservations:
          cpus: '0.25'
          memory: 1024M
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 30s
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://192.168.x.x:123"
networks:
  onlyoffice-net:
    driver: bridge
